### ISSUE TITLE
Basic GraphQL Question

### ISSUE THREAD

**Issue by MaximilianKindshofer** [reactql/example-auth#10]
I have a really basic question about GraphQL:

in the Session Type you define the user response field as follows:

```
            user: {
                type: UserType,
                resolve(obj) {
                    return obj.session && obj.session.getUser();
                }
```

Why do we have to return obj.session and obj.session.getUser()? Naively I would think it would be sufficient to just return obj.session.getUser();

If I try my Naive aproach I get this error message:

```
GraphQLError: Unknown operation named "null".
    at buildExecutionContext (/home/maximilian/code/reactql/bithive/node_modules/graphql/execution/execute.js:202:13)
    at executeImpl (/home/maximilian/code/reactql/bithive/node_modules/graphql/execution/execute.js:121:15)
```

Can you explain the syntax to me or hint me to the documentation. I searched at the Resolver part of the GraphQL documentation and the Resolver part in the Apollo Documentation and I think it could be somewhere in here:

https://www.apollographql.com/docs/graphql-tools/resolvers.html#Default-resolver

but to be frank I don't understand what's happening here

**Comment by leebenson** [comment]
`obj.session` is a sanity check to ensure a session has already been loaded against the user. If it hasn't, it will be null, and this `.sesson.getUser()` won't exist.

In other languages such as C# 7, for example, you might do this like:

```c#
return Obj.Session?.GetUser();
```

... but Javascript doesn't (yet) have support for inline null checking, so we use the side-effect of using the short-circuit nature of `&&` to _only_ bother running `obj.session.getUser()` if the left-side of the operand evaluates to a truthy value.

This is a JS concept, rather than anything specifically to do with GraphQL. If `obj.session` doesn't exist, the statement will return false and thus GraphQL will ignore the output. If it evaluates true, the right-side of the operation will return (i.e. `obj.session.getUser()`, which returns a Promise) and _that_ will become the result of the resolve method.
